## DATA - Telco Churn

In [246]:
import pandas as pd
from pathlib import Path

In [247]:
pd.set_option('display.max_columns', None)

In [248]:
PROCESSED_PATH = Path('../data/processed')
RAW_PATH = Path('../data/raw')

In [249]:
df = pd.read_csv(RAW_PATH / 'Telco-Customer-Churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [250]:
telco_df = df.copy()

In [251]:
telco_df[(telco_df['PhoneService'] == 0) & (telco_df['InternetService'] == 1)]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

In [252]:
telco_df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### Empezamos a cambiar datos

#### Gender

In [253]:
telco_df['gender'].unique()

array(['Female', 'Male'], dtype=object)

- Female - 0 
- Male - 1

In [254]:
telco_df['gender'] = telco_df['gender'].apply(lambda x : 0 if x == 'Female' else 1)
telco_df['gender'].unique()

array([0, 1])

#### Partner

In [255]:
telco_df['Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [256]:
telco_df['Partner'] = telco_df['Partner'].apply(lambda x: 0 if x == 'No' else 1)
telco_df['Partner'].unique()

array([1, 0])

#### Dependents

In [257]:
telco_df['Dependents'].unique()

array(['No', 'Yes'], dtype=object)

In [258]:
telco_df['Dependents'] = telco_df['Dependents'].apply(lambda x: 0 if x == 'No' else 1)
telco_df['Dependents'].unique()

array([0, 1])

#### Phone service

In [259]:
telco_df['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [260]:
telco_df['PhoneService'] = telco_df['PhoneService'].apply(lambda x: 0 if x == 'No' else 1)
telco_df['PhoneService'].unique()

array([0, 1])

#### Muliple Lines

In [261]:
telco_df['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

- No phone service = No = 0
- Yes = 1

In [262]:
telco_df['MultipleLines'] = telco_df['MultipleLines'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['MultipleLines'].unique()

array([0, 1])

#### Internet service

In [263]:
telco_df['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

- No - 0
- Fiber optic - 1
- DSL - 2

In [264]:
telco_df['InternetService'] = telco_df['InternetService'].apply(lambda x: 0 if x == 'No' else 1 if x == 'DSL' else 2)
telco_df['InternetService'].unique()

array([1, 2, 0])

#### Online Security

In [265]:
telco_df['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

- No internet service = No = 0
- Yes = 1

In [266]:
telco_df['OnlineSecurity'] = telco_df['OnlineSecurity'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['OnlineSecurity'].unique()

array([0, 1])

#### Online Backup

In [267]:
telco_df['OnlineBackup'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

- No internet service = No = 0
- Yes = 1

In [268]:
telco_df['OnlineBackup'] = telco_df['OnlineBackup'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['OnlineBackup'].unique()

array([1, 0])

#### Device Protection

In [269]:
telco_df['DeviceProtection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

- No internet service = No = 0
- Yes = 1

In [270]:
telco_df['DeviceProtection'] = telco_df['DeviceProtection'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['DeviceProtection'].unique()

array([0, 1])

#### Tech Support

In [271]:
telco_df['TechSupport'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

- No internet service = No = 0
- Yes = 1

In [272]:
telco_df['TechSupport'] = telco_df['TechSupport'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['TechSupport'].unique()

array([0, 1])

#### Streaming TV

In [273]:
telco_df['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

- No internet service = No = 0
- Yes = 1

In [274]:
telco_df['StreamingTV'] = telco_df['StreamingTV'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['StreamingTV'].unique()

array([0, 1])

#### Streaming Movies

In [275]:
telco_df['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [276]:
telco_df['StreamingMovies'] = telco_df['StreamingMovies'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['StreamingMovies'].unique()

array([0, 1])

- No internet service = No = 0
- Yes = 1

#### Contract

In [277]:
telco_df['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

- Month-to-month - 0
- One year - 1
- Two year - 2

In [278]:
telco_df['Contract'] = telco_df['Contract'].apply(lambda x: 0 if x == 'Month-to-month' else 1 if x == 'One year' else 2)
telco_df['Contract'].unique()

array([0, 1, 2])

#### Paperless Billing

In [279]:
telco_df['PaperlessBilling'].unique()

array(['Yes', 'No'], dtype=object)

In [280]:
telco_df['PaperlessBilling'] = telco_df['PaperlessBilling'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['PaperlessBilling'].unique()

array([1, 0])

#### Payment Method

In [281]:
telco_df['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

- Electronic check = Mailed check = 0
- Bank transfer (automatic) = Credit card (automatic) = 1

In [282]:
telco_df['PaymentMethod'] = telco_df['PaymentMethod'].apply(lambda x: 1 if x.__contains__('automatic') else 0)
telco_df['PaymentMethod'].unique()

array([0, 1])

#### Churn

In [283]:
telco_df['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [284]:
telco_df['Churn'] = telco_df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)
telco_df['Churn'].unique()

array([0, 1])

#### New DF

In [285]:
telco_df.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG       0              0        1           0       1   
1  5575-GNVDE       1              0        0           0      34   
2  3668-QPYBK       1              0        0           0       2   
3  7795-CFOCW       1              0        0           0      45   
4  9237-HQITU       0              0        0           0       2   

   PhoneService  MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0             0              0                1               0             1   
1             1              0                1               1             0   
2             1              0                1               1             1   
3             0              0                1               1             0   
4             1              0                2               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 1            0            0                0         1   
2                 0            0            0                0         0   
3                 1            1            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges TotalCharges  Churn  
0                 1              0           29.85        29.85      0  
1                 0              0           56.95       1889.5      0  
2                 1              0           53.85       108.15      1  
3                 0              1           42.30      1840.75      0  
4                 1              0           70.70       151.65      1

In [286]:
telco_df.loc[(telco_df['PhoneService'] == 1) & (telco_df['InternetService'] == 1)].count()

customerID          1739
gender              1739
SeniorCitizen       1739
Partner             1739
Dependents          1739
tenure              1739
PhoneService        1739
MultipleLines       1739
InternetService     1739
OnlineSecurity      1739
OnlineBackup        1739
DeviceProtection    1739
TechSupport         1739
StreamingTV         1739
StreamingMovies     1739
Contract            1739
PaperlessBilling    1739
PaymentMethod       1739
MonthlyCharges      1739
TotalCharges        1739
Churn               1739
dtype: int64

In [287]:
telco_df.count()

customerID          7043
gender              7043
SeniorCitizen       7043
Partner             7043
Dependents          7043
tenure              7043
PhoneService        7043
MultipleLines       7043
InternetService     7043
OnlineSecurity      7043
OnlineBackup        7043
DeviceProtection    7043
TechSupport         7043
StreamingTV         7043
StreamingMovies     7043
Contract            7043
PaperlessBilling    7043
PaymentMethod       7043
MonthlyCharges      7043
TotalCharges        7043
Churn               7043
dtype: int64

#### Only PhoneService

In [288]:
phone_df = telco_df[(telco_df['PhoneService'] == 1) & (telco_df['InternetService'] == 0)]
phone_df

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
11    7469-LKBCI       1              0        0           0      16   
16    8191-XWSZG       0              0        0           0      52   
21    1680-VDCWW       1              0        1           0      12   
22    1066-JKSGK       1              0        0           0       1   
33    7310-EGVHZ       1              0        0           0       1   
...          ...     ...            ...      ...         ...     ...   
7017  4807-IZYOZ       0              0        0           0      51   
7019  9710-NJERN       0              0        0           0      39   
7020  9837-FWLCH       1              0        1           1      12   
7030  0871-OPBXW       0              0        0           0       2   
7037  2569-WGERO       0              0        0           0      72   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  \
11               1              0                0               0   
16               1              0                0               0   
21               1              0                0               0   
22               1              0                0               0   
33               1              0                0               0   
...            ...            ...              ...             ...   
7017             1              0                0               0   
7019             1              0                0               0   
7020             1              0                0               0   
7030             1              0                0               0   
7037             1              0                0               0   

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
11               0                 0            0            0   
16               0                 0            0            0   
21               0                 0            0            0   
22               0                 0            0            0   
33               0                 0            0            0   
...            ...               ...          ...          ...   
7017             0                 0            0            0   
7019             0                 0            0            0   
7020             0                 0            0            0   
7030             0                 0            0            0   
7037             0                 0            0            0   

      StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
11                  0         2                 0              1   
16                  0         1                 0              0   
21                  0         1                 0              1   
22                  0         0                 0              0   
33                  0         0                 0              1   
...               ...       ...               ...            ...   
7017                0         2                 0              1   
7019                0         2                 0              0   
7020                0         0                 1              0   
7030                0         0                 1              0   
7037                0         2                 1              1   

      MonthlyCharges TotalCharges  Churn  
11             18.95        326.8      0  
16             20.65      1022.95      0  
21             19.80       202.25      0  
22             20.15        20.15      1  
33             20.20         20.2      0  
...              ...          ...    ...  
7017           20.65      1020.75      0  
7019           20.15          826      0  
7020           19.20          239      0  
7030           20.05        39.25      0  
7037           21.15       1419.4      0  

[1526 rows x 21 columns]

In [289]:
phone_df[['InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']].sum()

InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
dtype: int64

In [290]:
phone_df = phone_df.drop(columns=['InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies'])

In [291]:
phone_df.to_csv(PROCESSED_PATH / 'phone_service.csv', index = None)

#### Only InternetService

In [292]:
telco_df[(telco_df['InternetService'] == 2)]

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
4     9237-HQITU       0              0        0           0       2   
5     9305-CDSKC       0              0        0           0       8   
6     1452-KIOVK       1              0        0           1      22   
8     7892-POOKP       0              0        1           0      28   
12    8091-TTVAX       1              0        1           0      58   
...          ...     ...            ...      ...         ...     ...   
7034  0639-TSIQW       0              0        0           0      67   
7035  8456-QDAVC       1              0        0           0      19   
7039  2234-XADUH       0              0        1           1      72   
7041  8361-LTMKD       1              1        1           0       4   
7042  3186-AJIEK       1              0        0           0      66   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  \
4                1              0                2               0   
5                1              1                2               0   
6                1              1                2               0   
8                1              1                2               0   
12               1              1                2               0   
...            ...            ...              ...             ...   
7034             1              1                2               1   
7035             1              0                2               0   
7039             1              1                2               0   
7041             1              1                2               0   
7042             1              0                2               1   

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
4                0                 0            0            0   
5                0                 1            0            1   
6                1                 0            0            1   
8                0                 1            1            1   
12               0                 1            0            1   
...            ...               ...          ...          ...   
7034             1                 1            0            1   
7035             0                 0            0            1   
7039             1                 1            0            1   
7041             0                 0            0            0   
7042             0                 1            1            1   

      StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
4                   0         0                 1              0   
5                   1         0                 1              0   
6                   0         0                 1              1   
8                   1         0                 1              0   
12                  1         1                 0              1   
...               ...       ...               ...            ...   
7034                0         0                 1              1   
7035                0         0                 1              1   
7039                1         1                 1              1   
7041                0         0                 1              0   
7042                1         2                 1              1   

      MonthlyCharges TotalCharges  Churn  
4              70.70       151.65      1  
5              99.65        820.5      1  
6              89.10       1949.4      0  
8             104.80      3046.05      1  
12            100.35       5681.1      0  
...              ...          ...    ...  
7034          102.95      6886.25      1  
7035           78.70       1495.1      0  
7039          103.20       7362.9      0  
7041           74.40        306.6      1  
7042          105.65       6844.5      0  

[3096 rows x 21 columns]

In [293]:
internet_df = telco_df[(telco_df['PhoneService'] == 0) & (telco_df['InternetService'] != 0)]
internet_df

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     7590-VHVEG       0              0        1           0       1   
3     7795-CFOCW       1              0        0           0      45   
7     6713-OKOMC       0              0        0           0      10   
20    8779-QRDMV       1              1        0           0       1   
27    8665-UTDHZ       1              0        1           1       1   
...          ...     ...            ...      ...         ...     ...   
7003  4501-VCPFK       1              0        0           0      26   
7007  2274-XUATA       1              1        1           0      72   
7029  2235-DWLJU       0              1        0           0       6   
7036  7750-EYXWZ       0              0        0           0      12   
7040  4801-JZAZL       0              0        1           1      11   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  \
0                0              0                1               0   
3                0              0                1               1   
7                0              0                1               1   
20               0              0                1               0   
27               0              0                1               0   
...            ...            ...              ...             ...   
7003             0              0                1               0   
7007             0              0                1               1   
7029             0              0                1               0   
7036             0              0                1               0   
7040             0              0                1               1   

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0                1                 0            0            0   
3                0                 1            1            0   
7                0                 0            0            0   
20               0                 1            0            0   
27               1                 0            0            0   
...            ...               ...          ...          ...   
7003             0                 1            1            0   
7007             1                 1            1            1   
7029             0                 0            0            1   
7036             1                 1            1            1   
7040             0                 0            0            0   

      StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0                   0         0                 1              0   
3                   0         1                 0              1   
7                   0         0                 0              0   
20                  1         0                 1              0   
27                  0         0                 0              0   
...               ...       ...               ...            ...   
7003                0         0                 0              0   
7007                1         2                 1              1   
7029                1         0                 1              0   
7036                1         1                 0              0   
7040                0         0                 1              0   

      MonthlyCharges TotalCharges  Churn  
0              29.85        29.85      0  
3              42.30      1840.75      0  
7              29.75        301.9      0  
20             39.65        39.65      1  
27             30.20         30.2      1  
...              ...          ...    ...  
7003           35.75       1022.5      0  
7007           63.10      4685.55      0  
7029           44.40       263.05      0  
7036           60.65        743.3      0  
7040           29.60       346.45      0  

[682 rows x 21 columns]

In [294]:
internet_df[['PhoneService', 'MultipleLines']].sum()

PhoneService     0
MultipleLines    0
dtype: int64

In [295]:
internet_df = internet_df.drop(columns=['PhoneService', 'MultipleLines'])

In [296]:
internet_df.to_csv(PROCESSED_PATH / 'internet_service.csv', index = None)

#### Both Phone and Internet Service

In [297]:
phone_internet_df = telco_df[(telco_df['PhoneService'] != 0) & (telco_df['InternetService'] != 0)]
phone_internet_df

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
1     5575-GNVDE       1              0        0           0      34   
2     3668-QPYBK       1              0        0           0       2   
4     9237-HQITU       0              0        0           0       2   
5     9305-CDSKC       0              0        0           0       8   
6     1452-KIOVK       1              0        0           1      22   
...          ...     ...            ...      ...         ...     ...   
7035  8456-QDAVC       1              0        0           0      19   
7038  6840-RESVB       1              0        1           1      24   
7039  2234-XADUH       0              0        1           1      72   
7041  8361-LTMKD       1              1        1           0       4   
7042  3186-AJIEK       1              0        0           0      66   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  \
1                1              0                1               1   
2                1              0                1               1   
4                1              0                2               0   
5                1              1                2               0   
6                1              1                2               0   
...            ...            ...              ...             ...   
7035             1              0                2               0   
7038             1              1                1               1   
7039             1              1                2               0   
7041             1              1                2               0   
7042             1              0                2               1   

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
1                0                 1            0            0   
2                1                 0            0            0   
4                0                 0            0            0   
5                0                 1            0            1   
6                1                 0            0            1   
...            ...               ...          ...          ...   
7035             0                 0            0            1   
7038             0                 1            1            1   
7039             1                 1            0            1   
7041             0                 0            0            0   
7042             0                 1            1            1   

      StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
1                   0         1                 0              0   
2                   0         0                 1              0   
4                   0         0                 1              0   
5                   1         0                 1              0   
6                   0         0                 1              1   
...               ...       ...               ...            ...   
7035                0         0                 1              1   
7038                1         1                 1              0   
7039                1         1                 1              1   
7041                0         0                 1              0   
7042                1         2                 1              1   

      MonthlyCharges TotalCharges  Churn  
1              56.95       1889.5      0  
2              53.85       108.15      1  
4              70.70       151.65      1  
5              99.65        820.5      1  
6              89.10       1949.4      0  
...              ...          ...    ...  
7035           78.70       1495.1      0  
7038           84.80       1990.5      0  
7039          103.20       7362.9      0  
7041           74.40        306.6      1  
7042          105.65       6844.5      0  

[4835 rows x 21 columns]

In [298]:
phone_internet_df.to_csv(PROCESSED_PATH / 'phone_internet_service.csv', index = None)

In [299]:
telco_df.to_csv(PROCESSED_PATH / 'telco_churn.csv', index = None)

In [300]:
telco_df.iloc[:,0].count(), (phone_df.iloc[:,0].count() + internet_df.iloc[:,0].count() + phone_internet_df.iloc[:,0].count())

(np.int64(7043), np.int64(7043))